In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix,classification_report
# Load the dataset
df = pd.read_csv("/content/i08_GroundwaterStations_EnterpriseWaterManagement.csv")
# Print first five rows using head() function
df.head()

X             Y  OBJECTID           SITE_CODE      WELL_NAME  \
0 -1.327244e+07  4.297889e+06         1  359801N1192283W001           25N1   
1 -1.328492e+07  4.300645e+06         2  360002N1193402W001  22S24E23J001M   
2 -1.323144e+07  4.186422e+06         3  351657N1188601W001  32S29E04R001M   
3 -1.324147e+07  4.180520e+06         4  351224N1189502W001  32S28E22R001M   
4 -1.324200e+07  4.264421e+06         5  357360N1189560W001       EWMA #49   

             SWN  STN_ID WCR_NO  \
0   22S25E25N01M   54349    NaN   
1   22S24E23J01M   54350    NaN   
2  32S29E04R001M   54487    NaN   
3  32S28E22R001M   54488    NaN   
4            NaN   54499    NaN   

                                            LOC_DESC    WELL_USE  ...  \
0                                                NaN     Unknown  ...   
1                                                NaN     Unknown  ...   
2                                SE CORNER OF SE 1/4  Irrigation  ...   
3                                SE CORNER OF SE 1/4  Irrigation  ...   
4  Approximate well location. To be field confirmed.  Irrigation  ...   

  MSMT_COUNT                         STN_CMT            STN_MOD_DATE  \
0          0  Geographic Information Systems  2022/01/06 13:05:30+00   
1          0  Geographic Information Systems  2022/01/06 13:05:30+00   
2          0                             NaN  2023/09/26 08:45:22+00   
3          0                  Borehole Depth  2023/09/26 08:45:22+00   
4          0                             NaN  2021/12/15 17:54:56+00   

   STN_MOD_BY      SOURCE                                GlobalID  \
0         NaN  DWR EWM DB  {0FFC8A1A-C8B9-482D-A23F-0DEC92D52FB4}   
1         NaN  DWR EWM DB  {E50EC6CB-8584-4001-B2D2-330D8B19D863}   
2         NaN  DWR EWM DB  {09D8900C-1C84-4579-BE52-E3C5F42DFB4C}   
3         NaN  DWR EWM DB  {7C21E154-B7AF-4D09-B170-45426A561C1F}   
4         NaN  DWR EWM DB  {A8BEEF92-C0F0-4D27-894F-A1A658D129D6}   

  MONITORING_PROGRAM LAST_MEAS_SUBMITTING_ORG_NAME  \
0          VOLUNTARY                           NaN   
1          VOLUNTARY                           NaN   
2               SGMA                           NaN   
3               SGMA                           NaN   
4          VOLUNTARY                           NaN   

  LAST_MEAS_COOPERATING_ORG_NAME       LAST_UPDATED_DATE  
0                            NaN  2024/01/16 06:00:00+00  
1                            NaN  2024/01/16 06:00:00+00  
2                            NaN  2024/01/16 06:00:00+00  
3                            NaN  2024/01/16 06:00:00+00  
4                            NaN  2024/01/16 06:00:00+00  

[5 rows x 29 columns]

In [ ]:
df.isnull().sum()

X                                     0
Y                                     0
OBJECTID                              0
SITE_CODE                             0
WELL_NAME                             1
SWN                                4623
STN_ID                                0
WCR_NO                            39851
LOC_DESC                          39793
WELL_USE                              0
WELL_TYPE                             0
WELL_DEPTH                        32345
TOP_PRF                           36048
BOT_PRF                           36048
LAST_GSE                              0
LAST_RPE                              0
RP_DESC                             664
FIRST_MSMT_DATE                    1289
LAST_MSMT_DATE                     1288
MSMT_COUNT                            0
STN_CMT                           39957
STN_MOD_DATE                          0
STN_MOD_BY                        46490
SOURCE                                0
GlobalID                              0


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46490 entries, 0 to 46489
Data columns (total 29 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   X                               46490 non-null  float64
 1   Y                               46490 non-null  float64
 2   OBJECTID                        46490 non-null  int64  
 3   SITE_CODE                       46490 non-null  object 
 4   WELL_NAME                       46489 non-null  object 
 5   SWN                             41867 non-null  object 
 6   STN_ID                          46490 non-null  int64  
 7   WCR_NO                          6639 non-null   object 
 8   LOC_DESC                        6697 non-null   object 
 9   WELL_USE                        46490 non-null  object 
 10  WELL_TYPE                       46490 non-null  object 
 11  WELL_DEPTH                      14145 non-null  float64
 12  TOP_PRF                         

In [ ]:
df.drop(columns=["X","Y","STN_MOD_BY","SITE_CODE", "WELL_NAME", "SWN" ,"WCR_NO", "LOC_DESC", "WELL_USE", "WELL_TYPE", "WELL_TYPE", "RP_DESC", "FIRST_MSMT_DATE", "LAST_MSMT_DATE", "STN_CMT", "STN_MOD_DATE", "SOURCE", "GlobalID", "MONITORING_PROGRAM", "LAST_MEAS_SUBMITTING_ORG_NAME", "LAST_MEAS_SUBMITTING_ORG_NAME", "LAST_MEAS_COOPERATING_ORG_NAME"],inplace=True)

In [ ]:
df.dropna(inplace=True)

In [ ]:
df

OBJECTID  STN_ID  WELL_DEPTH  TOP_PRF  BOT_PRF  LAST_GSE  LAST_RPE  \
4             5   54499       714.0    300.0    714.0   771.500   771.500   
5             6   59284       485.0    460.0    480.0   156.250   158.390   
6             7   59285       325.0    300.0    320.0   156.370   158.810   
7             8   59286       210.0    175.0    205.0   156.370   158.880   
9            10   54094       275.0    150.0    275.0   157.200   157.200   
...         ...     ...         ...      ...      ...       ...       ...   
45957     45958   51711       600.0    300.0    600.0   219.000   219.000   
45989     45990   37248       298.0    200.0    298.0  2396.200  2398.100   
46379     46380   18640       139.0    121.0    139.0  2232.300  2233.300   
46393     46394   55378       150.0     60.0    140.0  2202.372  2203.372   
46394     46395   37216        97.0     95.0     97.0  2264.400  2264.400   

       MSMT_COUNT       LAST_UPDATED_DATE  
4               0  2024/01/16 06:00:00+00  
5               0  2024/01/16 06:00:00+00  
6               0  2024/01/16 06:00:00+00  
7               0  2024/01/16 06:00:00+00  
9               0  2024/01/16 06:00:00+00  
...           ...                     ...  
45957           9  2024/01/16 06:00:00+00  
45989          38  2024/01/16 06:00:00+00  
46379          33  2024/01/16 06:00:00+00  
46393          48  2024/01/16 06:00:00+00  
46394         154  2024/01/16 06:00:00+00  

[10304 rows x 9 columns]

In [ ]:
y = df['LAST_GSE'].values
X = df.drop(['LAST_GSE', 'LAST_UPDATED_DATE'], axis=1).values
# Create the train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
y_test = y_test.astype(int)
y_pred = y_pred.astype(int)
print(np.unique(y))

[-300.    -204.7   -204.685 ... 7269.    7278.    9999.   ]


In [ ]:
y_train = np.array(y_train)
y_test = np.array(y_test)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(len(X_train), len(y_train))

(8243, 7)
(2061, 7)
(8243,)
(2061,)
8243 8243


In [ ]:
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)
mae = mean_absolute_error(y_test, y_pred)
print('Mean Absolute Error:', mae)
r2 = r2_score(y_test, y_pred)
print('R-squared Score:', r2)

Mean Squared Error: 29.167163814320524
Mean Absolute Error: 1.6510307278020748
R-squared Score: 0.9999810053540532


In [ ]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

classification_rep = classification_report(y_test, y_pred)
print("\nClassification Report:")
print(classification_rep)

Confusion Matrix:
[[0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]

Classification Report:
              precision    recall  f1-score   support

        -300       0.00      0.00      0.00         2
        -298       0.00      0.00      0.00         0
        -284       0.00      0.00      0.00         0
        -204       0.00      0.00      0.00         1
        -198       0.00      0.00      0.00         0
        -195       0.00      0.00      0.00         0
        -151       0.00      0.00      0.00         1
        -150       0.00      0.00      0.00         0
        -131       0.00      0.00      0.00         1
        -123       0.00      0.00      0.00         1
        -122       0.00      0.00      0.00         0
        -101       0.00      0.00      0.00         0
         -96       0.00      0.00      0.00         1
         -63       0.00      0.00      0.00         0
         -55       0.00    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.